name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run commit script
        run: |
          python commit.py
          git config --global user.name "Artur Nayman"
          git config --global user.email "arturnaiman@gmail.com"
          git add .
          git commit -m "Daily commit $(date)" || echo "Nothing to commit"
          git push
