name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Configure Git user
        run: |
          git config --global user.name "Artur Nayman"
          git config --global user.email "arturnaiman@gmail.com"

      - name: Run commit script
        run: python commit.py

      - name: Commit changes
        run: |
          git add .
          git commit -m "Daily commit $(date)" || echo "Nothing to commit"

      - name: Pull latest changes and push
        run: |
          git pull --rebase
          git push
